### ISSUE TITLE
Doesn't work with Python 3.4

### ISSUE THREAD

**Issue by TimurNurlygayanov** [notifiers/notifiers#148]
Reproduced with Python 3.4:

```
Traceback (most recent call last):
File "advanced_scripts/send_list_of_proxies_to_slack.py", line 1, in <module>
from notifiers import get_notifier
File "/var/lib/buildagent/work/e227c3b9c4fdf640/env3/lib/python3.4/site-packages/notifiers/__init__.py", line 4, in <module>
from .core import get_notifier, all_providers
File "/var/lib/buildagent/work/e227c3b9c4fdf640/env3/lib/python3.4/site-packages/notifiers/core.py", line 35
return f'<Response,provider={self.provider.capitalize()},status={self.status}>'
                                                                                 ^
SyntaxError: invalid syntax
Process exited with code 1
```

**Comment by liiight** [comment]
Yep, notifiers is 3.6 and up. It shouldn't have let you install it though, it uses the requires_version keyword in setup.py... weird
